# Generated by Django 4.0.1 on 2022-12-03 13:17

from django.db import migrations, models
import django.utils.timezone
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='price')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='product_name')),
                ('date_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_from')),
                ('image', models.ImageField(default='uploads/users_placeholder.png', upload_to=product.models.nameFile, verbose_name='image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
