# Generated by Django 4.1.2 on 2023-05-19 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name='lastname')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_date')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
