# Generated by Django 4.1.2 on 2023-05-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lastname',
        ),
        migrations.AddField(
            model_name='attendance',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fullname'),
        ),
    ]
