# Generated by Django 4.0.1 on 2022-11-06 13:35

from django.db import migrations, models
import exercise.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='category')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('image', models.ImageField(default='uploads/users_placeholder.png', upload_to=exercise.models.nameFile, verbose_name='image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
